services:
  envoy-grpc-proxy:
    image: "envoyproxy/envoy:v1.22.0"
    volumes:
      - ${CONFIG_DIR}/envoy.yaml:/etc/envoy/envoy.yaml:ro
    network_mode: "host"
  web:
    image: "nyek0/overlord-web:latest"
    ports:
      - "80:3000/tcp"
  log-server:
    image: "nyek0/overlord-log-server:latest"
    env_file: "${CONFIG_DIR}/overlord.env"
    network_mode: "host"
  api-gateway:
    image: "nyek0/overlord-api-gateway:latest"
    env_file: "${CONFIG_DIR}/overlord.env"
    network_mode: "host"
    depends_on:
      log-server:
        condition: service_started
  device-gateway:
    image: "nyek0/overlord-device-gateway:latest"
    env_file: "${CONFIG_DIR}/overlord.env"
    network_mode: "host"
    depends_on:
      log-server:
        condition: service_started
  yeelight-connector:
    image: "nyek0/overlord-yeelight-connector:latest"
    env_file: "${CONFIG_DIR}/overlord.env"
    network_mode: "host"
    depends_on:
      log-server:
        condition: service_started
