services:
  web:
    image: "nyek0/overlord-web:latest"
    ports:
      - "80:3000/tcp"
  log-server:
    image: "nyek0/overlord-log-server:latest"
    ports:
      - "5551:5551/tcp"
      - "5552:5552/udp"
