services:
  web:
    image: "nyek0/overlord-web:latest"
    ports:
      - "80:3000/tcp"
  log-server:
    image: "nyek0/overlord-log-server:latest"
    ports:
      - "5555:5555/tcp"
      - "5552:5552/udp"
    networks:
      - internal
  api-gateway:
    image: "nyek0/overlord-api-gateway:latest"
    environment:
      LOG_API_HOST: log-server
      LOG_API_PORT: 5552
      LOG_LEVEL: DEBUG
    networks:
      - internal
    depends_on:
      log-server:
        condition: service_started
networks:
  internal:
    driver: bridge
