name: Overlord build/deploy pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Build services
        env:
          DOCKER_USER: ${{ secrets.DOCKER_AUTH_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_AUTH_TOKEN }}
        run: ./build.sh
